*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 13.05.2010 at 01:31:07 by user I020676
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDLE_GOODMOVETOP.                 " Global Data
  INCLUDE LZDLE_GOODMOVEUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDLE_GOODMOVEF00                       . " subprograms
  INCLUDE LZDLE_GOODMOVEI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDLE_GOODMOVEF...                 " Subprograms
* INCLUDE LZDLE_GOODMOVEO...                 " PBO-Modules
* INCLUDE LZDLE_GOODMOVEI...                 " PAI-Modules
