*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 06.05.2014 at 11:01:09 by user ARNOLDP1
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZLE_DEF_SPEDTOP.                  " Global Data
  INCLUDE LZLE_DEF_SPEDUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZLE_DEF_SPEDF00                        . " subprograms
  INCLUDE LZLE_DEF_SPEDI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZLE_DEF_SPEDF...                  " Subprograms
* INCLUDE LZLE_DEF_SPEDO...                  " PBO-Modules
* INCLUDE LZLE_DEF_SPEDI...                  " PAI-Modules
