*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 25.11.2013 at 10:23:34 by user I020676
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMM_TRANS_UPLOADTOP.              " Global Data
  INCLUDE LZMM_TRANS_UPLOADUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMM_TRANS_UPLOADF00                    . " subprograms
  INCLUDE LZMM_TRANS_UPLOADI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMM_TRANS_UPLOADF...              " Subprograms
* INCLUDE LZMM_TRANS_UPLOADO...              " PBO-Modules
* INCLUDE LZMM_TRANS_UPLOADI...              " PAI-Modules
