*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 26.11.2013 at 14:05:11 by user I020676
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMM_TRANS_MSEGTOP.                " Global Data
  INCLUDE LZMM_TRANS_MSEGUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMM_TRANS_MSEGF00                      . " subprograms
  INCLUDE LZMM_TRANS_MSEGI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMM_TRANS_MSEGF...                " Subprograms
* INCLUDE LZMM_TRANS_MSEGO...                " PBO-Modules
* INCLUDE LZMM_TRANS_MSEGI...                " PAI-Modules
